// KOANO narrative API — Checkpoint 4, Cluster 2.
// POST { address } → client-ready neighborhood narrative generated by the
// runtime model from provider data only. Clerk-protected. The response is a
// GENERATED text with the provenance rollup of its inputs — the UI labels it.

import { NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import { generateNarrative, generateNarrativeForAddress } from '../../../../lib/agents/narrative';
import { guardSpend } from '../../../../lib/koano-guard';
import { registry } from '../../../../lib/providers/registry';
import type { AddressCandidate } from '../../../../lib/providers/types';

export const dynamic = 'force-dynamic';
export const maxDuration = 60;

function isCandidate(v: unknown): v is AddressCandidate {
  if (!v || typeof v !== 'object') return false;
  const c = v as Record<string, unknown>;
  return (
    typeof c.id === 'string' &&
    typeof c.label === 'string' &&
    typeof c.latitude === 'number' &&
    Number.isFinite(c.latitude) &&
    typeof c.longitude === 'number' &&
    Number.isFinite(c.longitude)
  );
}

export async function POST(req: Request) {
  const { userId } = await auth();
  if (!userId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  let body: { address?: unknown; candidate?: unknown };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }
  const candidate = isCandidate(body.candidate) ? body.candidate : null;
  const address = typeof body.address === 'string' ? body.address.trim() : '';
  if (!candidate && !address) {
    return NextResponse.json({ error: '"address" or "candidate" is required' }, { status: 400 });
  }

  // Spend guard: approval + shared narrative/briefing rate limit + breaker.
  const guard = await guardSpend({ userId, kind: 'content', route: '/api/narrative' });
  if (!guard.ok) {
    return NextResponse.json(guard.body, { status: guard.status });
  }

  try {
    let result;
    if (candidate) {
      // Re-derive the confirmed address (BBL) from the user's pick, server-side.
      const rc = await registry.geocode.resolveCandidate(candidate);
      if (!rc.ok || !rc.data) throw new Error(rc.error ?? 'Could not resolve the selected address');
      result = await generateNarrativeForAddress(rc.data);
    } else {
      result = await generateNarrative(address);
    }
    return NextResponse.json(result);
  } catch (e) {
    return NextResponse.json(
      { error: e instanceof Error ? e.message : 'narrative generation failed' },
      { status: 422 },
    );
  }
}
