// KOANO narrative API — Checkpoint 4, Cluster 2.
// POST { address } → client-ready neighborhood narrative generated by the
// runtime model from provider data only. Clerk-protected. The response is a
// GENERATED text with the provenance rollup of its inputs — the UI labels it.

import { NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import { generateNarrative } from '../../../../lib/agents/narrative';
import { guardSpend } from '../../../../lib/koano-guard';

export const dynamic = 'force-dynamic';
export const maxDuration = 60;

export async function POST(req: Request) {
  const { userId } = await auth();
  if (!userId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  let body: { address?: unknown };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }
  const address = typeof body.address === 'string' ? body.address.trim() : '';
  if (!address) {
    return NextResponse.json({ error: '"address" is required' }, { status: 400 });
  }

  // Spend guard: approval + shared narrative/briefing rate limit + breaker.
  const guard = await guardSpend({ userId, kind: 'content', route: '/api/narrative' });
  if (!guard.ok) {
    return NextResponse.json(guard.body, { status: guard.status });
  }

  try {
    const result = await generateNarrative(address);
    return NextResponse.json(result);
  } catch (e) {
    return NextResponse.json(
      { error: e instanceof Error ? e.message : 'narrative generation failed' },
      { status: 422 },
    );
  }
}
